import 'package:flutter/material.dart';

const Color colorBlue = Color(0xFF007BFF);
const Color colorIndigo = Color(0xFF6610F2);
const Color colorPurple = Color(0xFF680DD8);
const Color colorPurple2 = Color(0xFF6F42C1);

List<String> brazilCities = [
  'Rio de Janeiro',
  'São Paulo',
  'Brasília',
  'Salvador',
  'Fortaleza',
  'Belo Horizonte',
  'Manaus',
  'Curitiba',
  'Recife',
  'Goiânia',
  'Belém',
  'Porto Alegre',
  'São Luís',
  'Natal',
  'Campo Grande',
  'Teresina',
  'João Pessoa',
  'Aracaju',
  'Cuiabá',
  'São Gonçalo',
  'Feira de Santana',
  'Olinda',
  'Nova Iguaçu',
  'Contagem',
  'São Bernardo do Campo',
  'Ribeirão Preto',
  'Mauá',
  'Santos',
  'Sorocaba',
  'Vila Velha',
  'Pelotas',
  'Londrina',
  'Juiz de Fora',
  'São José do Rio Preto',
  'Barueri',
  'Niterói',
  'Maringá',
  'Anápolis',
  'Nanuque',
  'Formiga',
  'Imbituba',
  'Guarapari',
  'Sertãozinho',
  'Três Pontas',
  'Cambuí',
  'Boa Esperança',
  'Varginha',
  'Araxá',
  'Itajubá',
  'Santa Rita do Sapucaí',
  'Poços de Caldas',
  'São Lourenço',
  'Pouso Alegre',
  'Lavras',
  'Alfenas',
  'Passos',
  'Piracicaba',
  'Lins',
  'Jaú',
  'Botucatu',
  'Araçatuba',
  'Birigui',
  'Ilha Solteira',
  'Tupã',
  'Adamantina',
  'Presidente Prudente',
  'Assis',
  'Marília',
  'Ourinhos',
  'São Carlos',
  'Araraquara',
  'Franca',
  'Ribeirão Preto',
  'Sertãozinho',
  'São José do Rio Preto',
  'Catanduva',
  'Jales',
  'Fernandópolis',
  'Votuporanga',
  'Santa Fé do Sul',
  'Aparecida',
  'Guaratinguetá',
  'Cruzeiro',
  'Pindamonhangaba',
  'São Sebastião',
  'Caraguatatuba',
  'Ubatuba',
  'Campos do Jordão',
  'Atibaia',
  'Bragança Paulista',
  'Itatiba',
  'Jundiaí',
  'Campinas',
  'Piracicaba',
  'Limeira',
  'Rio Claro',
  'Araras',
  'Lins',
  'São José dos Campos',
  'Santo André',
  'Osasco',
  'Santos',
  'Mauá',
  'São Bernardo do Campo',
  'Guarulhos',
  'Sorocaba',
  'Santana de Parnaíba',
  'Diadema',
  'Mogi das Cruzes',
  'Carapicuíba',
  'Itaquaquecetuba',
  'Barueri',
  'Piracicaba',
  'Bauru',
  'Franca',
  'Ribeirão Preto',
  'São José do Rio Preto',
  'Marília',
  'São Carlos',
  'Araraquara',
  'Presidente Prudente',
  'Taubaté',
  'Itapetininga',
  'Votuporanga',
  'Santa Fé do Sul',
  'Catanduva',
  'Rio Claro',
  'Sumaré',
  'Jundiaí',
  'Osasco',
  'Barueri',
  'Itapevi',
  'Suzano',
  'Cotia',
  'Embu das Artes',
  'Taboão da Serra',
  'São Caetano do Sul',
  'São José dos Campos',
  'São José do Rio Preto',
  'Sorocaba',
  'Santos',
  'Piracicaba',
  'Franca',
  'Guarujá',
  'Jundiaí',
  'Limeira',
  'Suzano',
  'Taboão da Serra',
  'São Carlos',
  'Embu-Guaçu',
  'Santana de Parnaíba',
  'Hortolândia',
  'Mogi das Cruzes',
  'Itaquaquecetuba',
  'São João da Boa Vista',
  'Itapeva',
  'Itu',
  'Lorena',
  'Andradina',
  'Sertãozinho',
  'Bragança Paulista',
  'Caraguatatuba',
  'Mairiporã',
  'Barretos',
  'Marília',
  'Botucatu',
  'Ourinhos',
  'Registro',
  'Avaré',
  'Tatuí',
  'Ituverava',
  'Santa Bárbara d\'Oeste',
  'Guararapes',
  'Matão',
  'Votuporanga',
  'Ibitinga',
  'Cruzeiro',
  'Santa Cruz do Rio Pardo',
  'Porto Ferreira',
  'Iguape',
  'Promissão',
  'Tietê',
  'Caconde',
  'Sertãozinho',
  'Ibitinga',
  'Espírito Santo do Pinhal',
  'Penápolis',
  'Novo Horizonte',
  'Capivari',
  'Mogi Mirim',
  'Santa Rosa de Viterbo',
  'São Joaquim da Barra',
  'Orlândia',
  'Batatais',
  'Barretos',
  'Pirassununga',
  'Itapira',
  'Jaboticabal',
  'Sertãozinho',
  'Votuporanga',
  'Matão',
  'Franca',
  'Bebedouro',
  'Catanduva',
  'Monte Aprazível',
  'Ituverava',
  'Olímpia',
  'José Bonifácio',
  'Palmital',
  'Santa Fé do Sul',
  'Novo Horizonte',
  'Penápolis',
  'São Joaquim da Barra',
  'Fernandópolis',
  'São José do Rio Pardo',
  'Jales',
  'Pindorama',
  'Américo Brasiliense',
  'Nova Granada',
  'Guaíra',
  'Olimpia',
  'Tanabi',
  'Sales Oliveira',
  'Cravinhos',
  'Araraquara',
  'São Simão',
  'São José do Rio Pardo',
  'Matão',
  'Guariba',
  'Sertãozinho',
  'Mogi-Guaçu',
  'Ituverava',
  'São Carlos',
  'Brodowski',
  'Mococa',
  'Orlândia',
  'Serrana',
  'Caconde',
  'Sertãozinho',
  'Guariba',
  'Monte Alto',
  'Itirapina',
  'Pirassununga',
  'São Carlos',
  'Ibaté',
  'Santa Rita do Passa Quatro',
  'Porto Ferreira',
  'Jaboticabal',
  'Santa Rosa de Viterbo',
  'Descalvado',
  'Santo Antônio da Posse',
  'Conchal',
  'Cosmópolis',
  'Hortolândia',
  'Monte Mor',
  'Nova Odessa',
  'Paulínia',
  'Sumaré',
  'Artur Nogueira',
  'Holambra',
  'Pedreira',
  'Jaguariúna',
  'Jarinu',
  'Socorro',
  'Louveira',
  'Biritiba-Mirim',
  'Ibirarema',
  'Gália',
  'Agudos',
  'Regente Feijó',
  'Lucianópolis',
  'Torrinha',
  'Florínia',
  'Potim',
  'Estiva Gerbi',
  'Charqueada',
  'Santa Cruz da Esperança',
  'Guará',
  'Ipiguá',
  'Analândia',
  'Sarapuí',
  'Pereiras',
  'Guatapará',
  'Santa Lúcia',
  'Fartura',
  'Guarantã',
  'Icém',
  'Santo Expedito',
  'Boa Esperança do Sul',
  'Nova Independência',
  'Presidente Alves',
  'Rifaina',
  'Santa Rosa de Viterbo',
  'Riolândia',
  'Santo Antônio do Jardim',
  'Santópolis do Aguapeí',
  'Cardoso',
  'Sebastianópolis do Sul',
  'Cafelândia',
  'Dumont',
  'Monte Castelo',
  'Nova Canaã Paulista',
  'Aparecida d\'Oeste',
  'Ouro Verde',
  'Piquerobi',
  'São João das Duas Pontes',
  'Auriflama',
  'Santa Salete',
  'Braúna',
  'Guaraci',
  'Piacatu',
  'Álvaro de Carvalho',
  'Bálsamo',
  'Dolcinópolis',
];
